try {  
    const b = 100; 
    const a = 1;  
    const c = a + b; 
    console.log(c);   
  } catch (err) {  
    console.log(err);  
  }  